// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (FeedFollow, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFeedFollow(ctx context.Context, arg DeleteFeedFollowParams) error
	DeleteFeedFollowByFeedId(ctx context.Context, arg DeleteFeedFollowByFeedIdParams) error
	GetFeedByURL(ctx context.Context, url string) (Feed, error)
	GetFeedFollows(ctx context.Context, userID uuid.UUID) ([]FeedFollow, error)
	GetFeeds(ctx context.Context) ([]Feed, error)
	GetNextFeedsToFetch(ctx context.Context, limit int32) ([]Feed, error)
	GetNextPostToSummarize(ctx context.Context) (Post, error)
	GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]Post, error)
	GetUserByAPIKey(ctx context.Context, apiKey string) (User, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	MarkFeedAsFetched(ctx context.Context, arg MarkFeedAsFetchedParams) (Feed, error)
	SearchPostsForUser(ctx context.Context, arg SearchPostsForUserParams) ([]Post, error)
	UpdatePostSummary(ctx context.Context, arg UpdatePostSummaryParams) error
}

var _ Querier = (*Queries)(nil)
