package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strings"
	"time"
	"strconv"
	"github.com/akshatasingh1/rssagg/internal/database"
	"github.com/google/uuid"
	"github.com/redis/go-redis/v9"
	"golang.org/x/crypto/bcrypt"
)

func (apiCfg *apiConfig) handlerCreateUser(w http.ResponseWriter, r *http.Request) {
	type parameters struct {
		Name     string `json:"name"`
		Email    string `json:"email"`
		Password string `json:"password"`
	}
	decoder := json.NewDecoder(r.Body)

	params := parameters{}
	err := decoder.Decode(&params)
	if err != nil {
		respondWithError(w, 400, fmt.Sprintf("Error parsing JSON: %v", err))
		return
	}

	params.Email = strings.TrimSpace(strings.ToLower(params.Email))
	if params.Name == "" || params.Email == "" || len(params.Password) < 8 {
		respondWithError(w, 400, "name, email, and a password of at least 8 characters are required")
		return
	}

	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(params.Password), bcrypt.DefaultCost)
	if err != nil {
		respondWithError(w, 500, "Failed to hash password")
		return
	}

	user, err := apiCfg.DB.CreateUser(r.Context(), database.CreateUserParams{
		ID:           uuid.New(),
		CreatedAt:    time.Now().UTC(),
		UpdatedAt:    time.Now().UTC(),
		Name:         params.Name,
		Email:        sql.NullString{String: params.Email, Valid: true},
		PasswordHash: sql.NullString{String: string(hashedPassword), Valid: true},
	})
	if err != nil {
		if strings.Contains(err.Error(), "duplicate key") {
			respondWithError(w, 409, "An account with this email already exists")
			return
		}
		respondWithError(w, 400, fmt.Sprintf("Failed to create user: %v", err))
		return
	}

	respondWithJSON(w, 201, databaseUsertoUser(user))
	log.Printf("User created with ID: %v", user.ID)
}

func (apiCfg *apiConfig) handlerLogin(w http.ResponseWriter, r *http.Request) {
	type parameters struct {
		Email    string `json:"email"`
		Password string `json:"password"`
	}
	decoder := json.NewDecoder(r.Body)

	params := parameters{}
	err := decoder.Decode(&params)
	if err != nil {
		respondWithError(w, 400, fmt.Sprintf("Error parsing JSON: %v", err))
		return
	}

	params.Email = strings.TrimSpace(strings.ToLower(params.Email))

	user, err := apiCfg.DB.GetUserByEmail(r.Context(), sql.NullString{String: params.Email, Valid: true})
	if err != nil {
		respondWithError(w, 401, "Invalid email or password")
		return
	}

	if !user.PasswordHash.Valid {
		respondWithError(w, 401, "Invalid email or password")
		return
	}

	err = bcrypt.CompareHashAndPassword([]byte(user.PasswordHash.String), []byte(params.Password))
	if err != nil {
		respondWithError(w, 401, "Invalid email or password")
		return
	}

	respondWithJSON(w, 200, databaseUsertoUser(user))
	log.Printf("User logged in: %v", user.ID)
}

func (apiCfg *apiConfig) handlerGetUser(w http.ResponseWriter, r *http.Request, user database.User) {
	respondWithJSON(w, 200, databaseUsertoUser(user))
}

// UPDATED: Now with Redis Read-Through Caching!


func (apiCfg *apiConfig) handlerGetPostsForUser(w http.ResponseWriter, r *http.Request, user database.User) {
	// 1. Read the "page" query parameter from the URL (default to 1)
	pageStr := r.URL.Query().Get("page")
	page := 1
	if pageStr != "" {
		parsedPage, err := strconv.Atoi(pageStr)
		if err == nil && parsedPage > 0 {
			page = parsedPage
		}
	}

	// 2. Calculate Limit and Offset
	limit := 50
	offset := (page - 1) * limit

	// 3. Create a unique Cache Key for this user AND this specific page!
	cacheKey := fmt.Sprintf("posts:user:%s:page:%d:v2", user.ID.String(), page)

	// 4. THE CACHE HIT: Check Redis first
	cachedData, err := apiCfg.RedisClient.Get(r.Context(), cacheKey).Result()
	if err == nil {
		log.Println("Cache HIT! Returning posts from Redis.")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(cachedData))
		return
	} else if err != redis.Nil {
		log.Printf("Redis error: %v", err)
	}

	// 5. THE CACHE MISS: Not in Redis, go to PostgreSQL
	log.Println("Cache MISS! Fetching from PostgreSQL.")
	posts, err := apiCfg.DB.GetPostsForUser(r.Context(), database.GetPostsForUserParams{
		UserID: user.ID,
		Limit:  int32(limit),
		Offset: int32(offset), // <--- The new Offset generated by sqlc!
	})
	if err != nil {
		respondWithError(w, 400, fmt.Sprintf("Failed to get posts for user: %v", err))
		return
	}

	// Convert DB models to JSON response format
	postsResponse := databasePostsToPosts(posts)

	// 6. Save to Redis for next time! (60 second Time-To-Live)
	postsJSON, marshalErr := json.Marshal(postsResponse)
	if marshalErr == nil {
		apiCfg.RedisClient.Set(r.Context(), cacheKey, postsJSON, 60*time.Second)
	}

	// 7. Send response to user
	respondWithJSON(w, 200, postsResponse)
}